# New .drone.yml content
pipeline:
  BuildStart:
    image: hpreston/drone-ansible-netdevops
    commands:
      - echo "Starting Build"
      - git fetch
      - git checkout master

  SparkNotify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, PERSONEMAIL ]
    message: "Build Done!"
    when:
      status: [ success, failure ]
