# New .drone.yml content
pipeline:
  BuildStart:
    image: hpreston/drone-ansible-netdevops
    commands:
      - echo "Starting Build"

  Integration-ConfigTestNetwork:
    image: hpreston/drone-ansible-netdevops
    commands:
      - "pip install -r requirements.txt"
  
  before_script:
    image: hpreston/drone-ansible-netdevops
    commands:
      - "yamllint --strict *.yml"

  SparkNotify:
    image: hpreston/drone-spark:0.7
    secrets: [ SPARK_TOKEN, personEmail, roomId, roomName ]
    message: "Build Done!"
    when:
      status: [ success, failure ]
