---

stages:
  - install
  - validate
  - deploy_to_test
  - deploy_to_prod

install:
  stage: install
  script:
    - sudo apt update
    - sudo apt install python3-pip
    - pip3 --version
    - pip3 install -r requirements.txt

lint:
  stage: validate
  script:
    - yamllint --strict *.yml

deploy_to_test:
  stage: deploy_to_test
  script:
    - echo "Deploy to test env"
    - ansible-playbook test.yml

