---

stages:
  - validate
  - deploy_to_test
  - deploy_to_prod

lint:
  - stage: validate
  - image: kecorbin/ansible:devel
  - script:
      - ansible-playbook --syntex-check ntp_config.yml test.yml

deploy_to_test:
  - stage: deploy_to_test
  - image: kecorbin/ansible:devel
  - script:
      - echo "Deploy to test env"
      - ansible-playbook test.yaml

deploy_to_prod:
  - stage: deploy_to_prod
  - image: kecorbin/ansible:devel
  - script:
      - echo "Deploy to prod env"
      - ansible-playbook ntp_config.yml
    when: manual
