---

stages:
  - validate
  - deploy_to_test
  - deploy_to_prod
  - verify_deploy_to_test
  - verify_deploy_to_prod

install:
  stage: install
  script:
    - pip install -r requirements.txt

lint:
  stage: validate
  script:
    - yamllint --strict *.yml

deploy_to_test:
  stage: deploy_to_test
  script:
<<<<<<< HEAD
    - "Deploy to test env"
    - ansible-playbook test.yml
=======
    - echo "Deploy to test env"
    - ansible-playbook test.yml

deploy_to_prod:
  image: kecorbin/ansible:devel
  stage: deploy_to_prod
  script:
    - echo "Deploy to prod env"
    - ansible-playbook ntp_config.yml
  when: manual
  allow_failure: false
>>>>>>> 3aaa1e16d51a460bb65c3dcb05d3544d4d0b0428
