---

stages:
  - validate
  - deploy_to_test
  - deploy_to_prod
  - verify_deploy_to_test
  - verify_deploy_to_prod

install:
  stage: install
  script:
    - pip install -r requirements.txt

lint:
  stage: validate
  script:
    - yamllint --strict *.yml

deploy_to_test:
  stage: deploy_to_test
  script:
    - "Deploy to test env"
    - ansible-playbook test.yml
