---
# Define the language and versions used. The CI system will create
# a Python virtualenv for each Python version to test it.
language: "python"
python:
  - "3.7"


# Install python packages for ansible and linters first.
install:
  - "pip install -r requirements.txt"

# Execute linting to catch minor errors before running the main playbook.
# Find all YAML files in the project and lint them in strict mode.
before_script:
  - "yamllint --strict *.yml"

# Perform playbook testing with on pre-existing virtual routers.
# A more complex pipeline might deploy on-demand routers ahead of time
# using Terraform rather than assume they already exist.
script:
  - "ansible-playbook test.yml"

deploy:
  provider: script
  script: "ansible-playbook ntp_config.yml"
  when: manual

notifications:
  webhooks:
    urls:
      - https://yhby8rxwxynitc4aosxgj4.hooks.webhookrelay.com
    on_success: always   # default: always
    on_failure: always  # default: always
    on_start: always     # default: never
    on_cancel: always    # default: always
    on_error: always    # default: always
